#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinHud Configuration File:
#  Variables:
#   - {line} to go to the next line
#   - {max_players} to get the max players
#   - {online_players} to get the online player count
#   - & for color coding
#   - {x} to get the player's x position
#   - {y} to get the player's y position
#   - {z} to get the player's z position
#   - {level} to get the player's level
#   - {tps} to get the ticks per second
#   - {motd} to get the message of the day
#   - {money} to get the player's money
#   - {player} to get the player's name

#  Default Config:
#    hud-message: "&bBlazinHud &aby &6BlazeTheDev&r {line} &c{online_players}&f/&c{max_players}"
#    multi-world: "off"
#    worlds:
#     - "world"

# The below config is the hud message that will be displayed above your hotbar
hud-message: "&bBlazinHud &aby &6BlazeTheDev&r {line} &c{online_players}&f/&c{max_players}"

# The below config turns on the ability to use {money} variable in your hud message (OPTIONS: on and off)
economy: "off"

# The below config turns on or off multi-world support (NOTE: the 2 options here are on and off)
multi-world: "off"

# The below config is the world names that are supported for the hud (NOTE: If multi-world config is off then this will be useless)
worlds:
 - "world"